// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: eidf

#ifndef _EIDF_UI_H
#define _EIDF_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_screen_screen1.h"

///////////////////// VARIABLES ////////////////////

// EVENTS

extern lv_obj_t * ui_startevents____initial_actions0;

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
