// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: eidf

#include "../ui.h"

lv_obj_t * ui_screen_screen1 = NULL;
lv_obj_t * ui_screen1_spinner_spinner1 = NULL;
lv_obj_t * ui_screen1_spinner_spinner2 = NULL;
lv_obj_t * ui_screen1_spinner_spinner3 = NULL;
lv_obj_t * ui_screen1_spinner_spinner4 = NULL;
// event funtions

// build funtions

void ui_screen_screen1_screen_init(void)
{
    ui_screen_screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen_screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_screen1_spinner_spinner1 = lv_spinner_create(ui_screen_screen1);
    //lv_spinner_set_anim_params(ui_screen1_spinner_spinner1, 1000, 90);
    lv_obj_set_width(ui_screen1_spinner_spinner1, 80);
    lv_obj_set_height(ui_screen1_spinner_spinner1, 80);
    lv_obj_remove_flag(ui_screen1_spinner_spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_screen1_spinner_spinner2 = lv_spinner_create(ui_screen_screen1);
    //lv_spinner_set_anim_params(ui_screen1_spinner_spinner2, 1000, 90);
    lv_obj_set_width(ui_screen1_spinner_spinner2, 80);
    lv_obj_set_height(ui_screen1_spinner_spinner2, 80);
    lv_obj_set_align(ui_screen1_spinner_spinner2, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_screen1_spinner_spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_screen1_spinner_spinner3 = lv_spinner_create(ui_screen_screen1);
    //lv_spinner_set_anim_params(ui_screen1_spinner_spinner3, 1000, 90);
    lv_obj_set_width(ui_screen1_spinner_spinner3, 80);
    lv_obj_set_height(ui_screen1_spinner_spinner3, 80);
    lv_obj_set_align(ui_screen1_spinner_spinner3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_remove_flag(ui_screen1_spinner_spinner3, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_screen1_spinner_spinner4 = lv_spinner_create(ui_screen_screen1);
    //lv_spinner_set_anim_params(ui_screen1_spinner_spinner4, 1000, 90);
    lv_obj_set_width(ui_screen1_spinner_spinner4, 80);
    lv_obj_set_height(ui_screen1_spinner_spinner4, 80);
    lv_obj_set_align(ui_screen1_spinner_spinner4, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_remove_flag(ui_screen1_spinner_spinner4, LV_OBJ_FLAG_CLICKABLE);      /// Flags

}

void ui_screen_screen1_screen_destroy(void)
{
    if(ui_screen_screen1) lv_obj_del(ui_screen_screen1);

    // NULL screen variables
    ui_screen_screen1 = NULL;
    ui_screen1_spinner_spinner1 = NULL;
    ui_screen1_spinner_spinner2 = NULL;
    ui_screen1_spinner_spinner3 = NULL;
    ui_screen1_spinner_spinner4 = NULL;

}
