// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: eidf

#ifndef UI_SCREEN_SCREEN1_H
#define UI_SCREEN_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_screen1
extern void ui_screen_screen1_screen_init(void);
extern void ui_screen_screen1_screen_destroy(void);
extern lv_obj_t * ui_screen_screen1;
extern lv_obj_t * ui_screen1_spinner_spinner1;
extern lv_obj_t * ui_screen1_spinner_spinner2;
extern lv_obj_t * ui_screen1_spinner_spinner3;
extern lv_obj_t * ui_screen1_spinner_spinner4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

